name: Release Broker

on:
  push:
    tags:
      - "*"

jobs:
  build_python_wheels:
    name: Build wheels ${{ matrix.os }} - python ${{ matrix.python }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        python: ["3.10", "3.11"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.1'

      - name: Install poetry
        run:
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Build wheels
        run: |
          export PATH="/Users/runner/.local/bin:$PATH"
          cp -r broker dagorama-broker/broker
          cd dagorama-broker
          poetry install
          poetry build
      - name: List wheels
        run: |
          cd dagorama-broker/dist
          ls -ls
      - uses: actions/upload-artifact@v3
        with:
          path: dagorama-broker/dist/*.whl

  publish_python_package:
    name: Publish python package
    needs: [build_python_wheels]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dagorama-broker/dist

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install poetry
        run:
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Build sdist static artifact
        run: |
          cp -r broker dagorama-broker/broker
          cd dagorama-broker
          poetry install
          poetry build --format sdist
      - name: Publish
        run: |
          cd dagorama-broker
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
