name: Dagorama Tests

on:
  push

jobs:
  run_python_tests:
    name: Run python tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.1'

      - name: Install go dependencies
        run: |
          (cd broker && go install)
          ./build.sh

      - name: Install poetry
        run:
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install python dependencies
        run: |
          export PATH="/Users/runner/.local/bin:$PATH"
          poetry install
          cp -r broker ./dagorama-broker
          poetry run pip install -e ./dagorama-broker

      - name: Run tests
        run: |
          poetry run pytest

  run_tests:
    name: Run golang tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.1'

      - name: Install dependencies
        run: |
          cd broker
          go install

      - name: Run tests
        run: |
          cd broker
          go test -v .

      - name: Run race condition tests
        run: |
          cd broker
          go test -v -race .

  run_typehinting:
    name: Run typehinting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        run:
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install
        run: |
          export PATH="/Users/runner/.local/bin:$PATH"
          poetry install

      - name: Run typehinting
        run: |
          poetry run mypy .
